### ISSUE TITLE
Molinillo::Resolver failing specs (fixtures missing)

### ISSUE THREAD

**Issue by ctrochalakis** [CocoaPods/Molinillo#23]
Hello,

I am running the specs on the git repository and 2 specs are failing, probably because fixtures are missing. Is it possible to include them?

Thank you

```
bundle exec bacon spec/dependency_graph_spec.rb spec/resolver_spec.rb spec/state_spec.rb

Molinillo::DependencyGraph
  in general
    ✓ returns root vertices by name
    ✓ returns vertices by name
    ✓ returns nil for non-existant root vertices
    ✓ returns nil for non-existant vertices
  detaching a node
    ✓ detaches a root vertex without successors
    ✓ detaches a root vertex with successors
    ✓ detaches a root vertex with successors with other parents

Molinillo::Resolver
  dependency resolution
  in general
    - can resolve a list of 0 requirements [FAILED]
    - includes the source of a user-specified unsatisfied dependency [FAILED]

Molinillo::ResolutionState
  Molinillo::DependencyState
    ✓ pops a possibility state

Errno::ENOENT: No such file or directory - spec/resolver_integration_specs/index/awesome.json
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `initialize': in general - can resolve a list of 0 requirements
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `open'
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `initialize'
	spec/resolver_spec.rb:96:in `new'
	spec/resolver_spec.rb:96:in `block (3 levels) in <module:Molinillo>'
	spec/resolver_spec.rb:99:in `block (2 levels) in <module:Molinillo>'
	spec/resolver_spec.rb:94:in `block in <module:Molinillo>'
	spec/resolver_spec.rb:60:in `<module:Molinillo>'
	spec/resolver_spec.rb:5:in `<top (required)>'

Errno::ENOENT: No such file or directory - spec/resolver_integration_specs/index/awesome.json
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `initialize': in general - includes the source of a user-specified unsatisfied dependency
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `open'
	/home/yatiohi/source/Molinillo/spec/spec_helper/index.rb:7:in `initialize'
	spec/resolver_spec.rb:96:in `new'
	spec/resolver_spec.rb:96:in `block (3 levels) in <module:Molinillo>'
	spec/resolver_spec.rb:104:in `block (2 levels) in <module:Molinillo>'
	spec/resolver_spec.rb:94:in `block in <module:Molinillo>'
	spec/resolver_spec.rb:60:in `<module:Molinillo>'
	spec/resolver_spec.rb:5:in `<top (required)>'

10 specifications (22 requirements), 0 failures, 2 errors
rake aborted!
```

**Comment by kylef** [comment]
It seems you didn't checkout the submodules, the resolver integration specs are in a submodule.

Can you try running the following:

```bash
$ rake bootstrap
```
